import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://avcicjfcocjdhrvgesnx.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2Y2ljamZjb2NqZGhydmdlc254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODM5NDI1MTMsImV4cCI6MTk5OTUxODUxM30.saZQAgSqkd54oXYEAioH0oBmqjAQ_BVodOz1TEW4hT8')